### ISSUE TITLE
readme.md link not working

### ISSUE THREAD

**Issue by mastef** [kamilgrzegorczyk/pods-framework-examples#1]
Hi Kamil,

 the last link from the readme.md ends up pointing to a robots.txt file

**Comment by kamilgrzegorczyk** [comment]
Hello,

That is strange - but all the links are working for me.

**Comment by mastef** [comment]
It's working now after a hard-refresh

Maybe a cache server misbehaviour, returning the last viewed url?

To specify : 
When I went to http://lowgravity.pl/blog/introduction-to-podsframework-2-x-part-4-simple-plugin/ [http://lowgravity.pl/blog/introduction-to-podsframework-2-x-part-4-simple-plugin/]
I saw the contents of : http://lowgravity.pl/robots.txt [http://lowgravity.pl/robots.txt]

The URL remained unchanged, it was not a forward

**Comment by kamilgrzegorczyk** [comment]
Maybe for whatever reason CDN got crazy. Anyway I am glad that this works for you now.
