### ISSUE TITLE
How to show draft pods (not only published)

### ISSUE THREAD

**Issue by RomanNagornyi** [kamilgrzegorczyk/pods-framework-examples#2]
Hello

I have created LGPodsAdmin.php for displaying a custom menu on admin panel. But it only shows published pods, how can I apply this functionality to draft or others statuses of pods?

Thanks in advance!

**Comment by kamilgrzegorczyk** [comment]
Honestly I wrote this code 5 years ago and did not use too much pods since something like 4 years. 

In a free time I will try to dig it up or you but my library is outdated anyway for sure.

**Comment by kamilgrzegorczyk** [comment]
@RomanNagornyi I believe you need to add where clause to UI object and type something like:

```
$object->ui = array(
            'item'   => 'genre',
            'items'  => 'genres',
            'where' => 't.post_status = "private" OR t.post_status="other"',
            'fields' => array(
                'add'       => $fields,
                'edit'      => $fields,
                'duplicate' => $fields,
                'manage'    => $fields,
            ),
        )
```

But I am unable to test that theory ;) 
Please let me know if that works!

If not then I could help you on site but due to the fact that this is my primary job I cannot offer such services as community help.

**Comment by RomanNagornyi** [comment]
Thanks for helping!

I have tried to apply code in a different variation. Also found some post (https://pods.io/forums/topic/pods_ui-where-fiter-list/).  And it's strange but following code works ))

```php
$object->ui = array(
		'item'   => 'genre',
		'items'  => 'genres',
		'where' => array( 'manage' => "t.post_status IN ( 'publish', 'pending', 'draft', 'auto-draft', 'future', 'private', 'inherit')" ),
		'fields' => array(
			'add'       => $fields,
			'edit'      => $edit_fields,
			'duplicate' => $edit_fields,
			'manage'    => $manage_fields,
		),
	);
```

**Comment by kamilgrzegorczyk** [comment]
Great that this works for you!
